version: '3'
services:
  xander-admin:
    image: xander/xander-admin:1.0-SNAPSHOT
    container_name: xander-admin
    ports:
      - 8080:8080
    volumes:
      - /mydata/app/xander-admin/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - mysql:db #可以用db这个域名访问mysql服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  xander-search:
    image: xander/xander-search:1.0-SNAPSHOT
    container_name: xander-search
    ports:
      - 8081:8081
    volumes:
      - /mydata/app/xander-search/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
      - mysql:db #可以用db这个域名访问mysql服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  xander-portal:
    image: xander/xander-portal:1.0-SNAPSHOT
    container_name: xander-portal
    ports:
      - 8085:8085
    volumes:
      - /mydata/app/xander-portal/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - mongo:mongo #可以用mongo这个域名访问mongo服务
      - mysql:db #可以用db这个域名访问mysql服务
      - rabbitmq:rabbit #可以用rabbit这个域名访问rabbitmq服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  xander-auth:
    image: xander/xander-auth:1.0-SNAPSHOT
    container_name: xander-auth
    ports:
      - 8401:8401
    volumes:
      - /mydata/app/xander-auth/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  xander-gateway:
    image: xander/xander-gateway:1.0-SNAPSHOT
    container_name: xander-gateway
    ports:
      - 8201:8201
    volumes:
      - /mydata/app/xander-gateway/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  xander-monitor:
    image: xander/xander-monitor:1.0-SNAPSHOT
    container_name: xander-monitor
    ports:
      - 8101:8101
    volumes:
      - /mydata/app/xander-monitor/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务